# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AhrU52n7kfO35KnJwqXINOq7cB2qtXFV

#Integrating dataset by creating API
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

! kaggle datasets download -d salader/dogs-vs-cats

"""#Unzip the dataset"""

import zipfile
zip_ref = zipfile.ZipFile('/content/dogs-vs-cats.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

"""#Importing all libraries we need"""

import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten,BatchNormalization,Dropout
import matplotlib.pyplot as plt
import numpy as np
import cv2
import os
import pandas as pd
from tqdm import tqdm

"""#Generator"""

train_ds = tf.keras.utils.image_dataset_from_directory(
        directory='/content/train',
        labels='inferred',
        label_mode='binary',
        batch_size=32,
        image_size=(256,256),
        validation_split=0.2,
        subset='training',
        seed=42
)

val_ds = tf.keras.utils.image_dataset_from_directory(
        directory='/content/test',
        labels='inferred',
        label_mode='binary',
        batch_size=32,
        image_size=(256,256),
        validation_split=0.2,
        subset='validation',
        seed=42
)

"""#Normalize"""

def process(image, label):
  image = tf.cast(image/255. , tf.float32)
  return image, label

train_ds = train_ds.map(process)
val_ds = val_ds.map(process)

"""#Creating CNN Model"""

def create_model():
  model = Sequential([

  Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(256,256,3)),
  BatchNormalization(),
  MaxPooling2D(pool_size=(2,2)),

  Conv2D(64, kernel_size=(3,3), activation='relu'),
  BatchNormalization(),
  MaxPooling2D(pool_size=(2,2)),

  Conv2D(128, kernel_size=(3,3), activation='relu'),
  BatchNormalization(),
  MaxPooling2D(pool_size=(2,2)),

  Flatten(),
  Dense(128, activation='relu'),
  Dropout(0.1),
  Dense(1, activation='sigmoid')
  ])

  model.compile(
      optimizer='adam',
      loss='binary_crossentropy',
      metrics=['accuracy']
  )

  return model

model=create_model()
model.summary()
history = model.fit(train_ds, epochs=10, validation_data=val_ds)

"""#Save model"""

model.save('model.h5')
print("\nModel saved as model.h5")

def generate_reference_predictions(model, class_names=['cats', 'dogs']):
    os.makedirs('predictions', exist_ok=True)

    for class_name in class_names:
        print(f"\nProcessing {class_name} images...")
        class_dir = os.path.join('/content/train', class_name)
        image_files = os.listdir(class_dir)
        predictions = []

        for img_file in tqdm(image_files):
            img_path = os.path.join(class_dir, img_file)
            img = cv2.imread(img_path)

            if img is not None:
                img = cv2.resize(img, (256,256))
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                img = img / 255.0
                img = np.expand_dims(img, axis=0)
                pred = model.predict(img, verbose=0)[0][0]
                predictions.append([img_file, pred])

        df = pd.DataFrame(predictions, columns=['filename', 'pred_value'])
        df.to_csv(f'predictions/{class_name.lower()}_predictions.csv', index=False)
        print(f"Saved {len(predictions)} {class_name} predictions")

def find_similar_images(model, img_path, num_similar=6):
    img = cv2.imread(img_path)
    if img is None:
        print("Error: Image not found!")
        return None

    plt.figure(figsize=(5, 5))
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title("Input Image")
    plt.axis('off')
    plt.show()

    img = cv2.resize(img, (256,256))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255.0
    img_input = np.expand_dims(img, axis=0)

    prediction = model.predict(img_input, verbose=0)[0][0]
    class_name = 'dog' if prediction > 0.5 else 'cat'
    confidence = prediction if class_name == 'dog' else 1 - prediction

    print(f"Predicted: {class_name.capitalize()} ({confidence:.2%} confidence)")
    csv_file = f'/content/predictions/dogs_predictions.csv' if class_name == 'dog' else f'/content/predictions/cats_predictions.csv'
    try:
        df = pd.read_csv(csv_file)
    except FileNotFoundError:
        print("Reference predictions not found. Run generate_reference_predictions() first.")
        return None

    df['distance'] = abs(df['pred_value'] - prediction)
    similar = df.sort_values('distance').head(num_similar)

    plt.figure(figsize=(15, 5))
    for i, (_, row) in enumerate(similar.iterrows()):
        folder_name = 'dogs' if class_name == 'dog' else 'cats'
        img_path = os.path.join('/content/train', folder_name, row['filename'])
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (256,256))

        plt.subplot(1, num_similar, i + 1)
        plt.imshow(img)
        plt.title(f"Similarity: {1 - row['distance']:.2f}")
        plt.axis('off')

    plt.suptitle(f"Most similar {class_name.capitalize()} images")
    plt.tight_layout()
    plt.show()

    return similar

generate_reference_predictions(model)

# Optional: Test on a sample image
sample_path = '/sample_images/images.jpeg'  # Update path
find_similar_images(model, sample_path)

sample_path = '/sample_images/cat.jpeg'  # Update path
find_similar_images(model, sample_path)

